#include <iostream>
using namespace std;
main() {
int num1 , num2 , num3 , num4 , num5 , num6 , num7 , num8 , num9 , num10 , num11 , num12 , num13 , num14 , num15 ;
int addition;
cout << " number 1: " ;
cin>> num1 ;
cout << " number 2 : " ;
cin>> num2 ;
cout << " number 3 : " ;
cin>> num3 ;
cout << " number 4 : " ;
cin>> num4 ;
cout << " number 5 : " ;
cin>> num5 ;
addition = num1 +num2 +num3 +num4 +num5 ;
int multiplication;
cout << " number 6: " ;
cin>> num6 ;
cout << " number 7 : " ;
cin>> num7 ;
cout << " number 8 : " ;
cin>> num8 ;
cout << " number 9 : " ;
cin>> num9 ;
cout << " number 10 : " ;
cin>> num10 ;
multiplication = num6 * num7 * num8 * num9 * num10 ;
int subtraction;
cout << " number 11: " ;
cin>> num11 ;
cout << " number 12 : " ;
cin>> num12 ;
cout << " number 13 : " ;
cin>> num13 ;
cout << " number 14 : " ;
cin>> num14 ;
cout << " number 15 : " ;
cin>> num15 ;
subtraction = num11 - num12 - num13 - num14 - num15 ;
int result = addition + multiplication - ( subtraction ) ;
cout<< " the final result is : " << result << endl;
   }
